
package se.vgregion.metaservice.vocabularyservice.intsvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import se.vgr.metaservice.schema.response.v1.LastChangeResponseObjectType;
import se.vgr.metaservice.schema.response.v1.LookupResponseObjectType;
import se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType;
import se.vgr.metaservice.schema.response.v1.ResponseObjectType;
import se.vgr.metaservice.schema.response.v1.XMLResponseObjectType;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.AddVocabularyNodeRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.FindNodesByNameRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.FindNodesRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.GetNamespaceXmlRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.GetVocabularyRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.LastChangeRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.LookupWordRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.MoveVocabularyNodeRequest;
import vocabularyservices.wsdl.metaservice_vgr_se.v2.UpdateVocabularyNodeRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VocabularyService", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    se.vgr.metaservice.schema.request.v1.ObjectFactory.class,
    se.vgr.metaservice.schema.document.v1.ObjectFactory.class,
    se.vgr.metaservice.schema.node.v2.ObjectFactory.class,
    se.vgr.metaservice.schema.response.v1.ObjectFactory.class,
    vocabularyservices.wsdl.metaservice_vgr_se.v2.ObjectFactory.class
})
public interface VocabularyService {


    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.ResponseObjectType
     */
    @WebMethod(operationName = "AddVocabularyNode")
    @WebResult(name = "AddVocabularyNodeResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public ResponseObjectType addVocabularyNode(
        @WebParam(name = "AddVocabularyNodeRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        AddVocabularyNodeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.ResponseObjectType
     */
    @WebMethod(operationName = "UpdateVocabularyNode")
    @WebResult(name = "UpdateVocabularyNodeResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public ResponseObjectType updateVocabularyNode(
        @WebParam(name = "UpdateVocabularyNodeRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        UpdateVocabularyNodeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.LookupResponseObjectType
     */
    @WebMethod(operationName = "LookupWord")
    @WebResult(name = "LookupWordResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public LookupResponseObjectType lookupWord(
        @WebParam(name = "LookupWordRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        LookupWordRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType
     */
    @WebMethod(operationName = "FindNodes")
    @WebResult(name = "FindNodesByNameResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public NodeListResponseObjectType findNodes(
        @WebParam(name = "FindNodesRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        FindNodesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.LastChangeResponseObjectType
     */
    @WebMethod(operationName = "GetLastChange")
    @WebResult(name = "LastChangeResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public LastChangeResponseObjectType getLastChange(
        @WebParam(name = "LastChangeRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        LastChangeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.ResponseObjectType
     */
    @WebMethod(operationName = "MoveVocabularyNode")
    @WebResult(name = "MoveVocabularyNodeResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public ResponseObjectType moveVocabularyNode(
        @WebParam(name = "MoveVocabularyNodeRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        MoveVocabularyNodeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType
     */
    @WebMethod(operationName = "FindNodesByName")
    @WebResult(name = "FindNodesByNameResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public NodeListResponseObjectType findNodesByName(
        @WebParam(name = "FindNodesByNameRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        FindNodesByNameRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.XMLResponseObjectType
     */
    @WebMethod(operationName = "GetNamespaceXml")
    @WebResult(name = "GetNamespaceXmlResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public XMLResponseObjectType getNamespaceXml(
        @WebParam(name = "GetNamespaceXmlRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        GetNamespaceXmlRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType
     */
    @WebMethod(operationName = "GetVocabulary")
    @WebResult(name = "GetVocabularyResponse", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    public NodeListResponseObjectType getVocabulary(
        @WebParam(name = "GetVocabularyRequest", targetNamespace = "urn:VocabularyServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
        GetVocabularyRequest parameters);

}
